version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: hermes
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: hermes_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://hermes:password123@db:5432/hermes_db?schema=public"
      NEXTAUTH_SECRET: "secret-super-seguro-gerado-com-openssl"
      NEXTAUTH_URL: "http://localhost:3000"
    depends_on:
      - db
    # Executa a migration antes de iniciar a aplicacao (apenas se necessario)
    # command: sh -c "npx prisma migrate deploy && node server.js"

volumes:
  pgdata:
